// src/components/History.svelte
<script lang="ts">
  import { history } from '../stores/history';
  import Ps1 from './Ps1.svelte';
</script>

{#each $history as { command, outputs }}
  <div>
    <div class="flex flex-row">
      <Ps1 />

      <p class="text-white px-3">{command}</p>
    </div>

    {#each outputs as output}
      <p class="text-white whitespace-pre-wrap">{output}</p>
    {/each}
  </div>
{/each}

// src/components/history/History.tsx
import React from 'react';
import { History as HistoryInterface } from '../../interfaces/history';
import { Ps1 } from '../ps1';

export const History: React.FC<{ history: Array<HistoryInterface> }> = ({
  history,
}) => {
  return (
    <>
      {history.map((entry: HistoryInterface, index: number) => (
        <div key={entry.command + index}>
          <div className="flex flex-row space-x-2">
            <div className="flex-shrink">
              <Ps1 />
            </div>

            <div className="flex-grow">{entry.command}</div>
          </div>

          <p
            className="whitespace-pre-wrap mb-2"
            style={{ lineHeight: 'normal' }}
            dangerouslySetInnerHTML={{ __html: entry.output }}
          />
        </div>
      ))}
    </>
  );
};

export default History;
